[provider]
cluster = "devnet"
wallet = "./tests/test-keypairs/test-key.json"

[programs.mainnet]
solana_nft_programs_rewards_center = "2T8nXEEvXVYNeNVrjWGbF1wLKkavPef7281tLbFTNo76"

[programs.devnet]
solana_nft_programs_rewards_center = "2T8nXEEvXVYNeNVrjWGbF1wLKkavPef7281tLbFTNo76"

[programs.testnet]
solana_nft_programs_rewards_center = "2T8nXEEvXVYNeNVrjWGbF1wLKkavPef7281tLbFTNo76"

[programs.localnet]
solana_nft_programs_rewards_center = "2T8nXEEvXVYNeNVrjWGbF1wLKkavPef7281tLbFTNo76"
